// This is the list of all slideshows that will be registered on the
// website, don't forget to register your new slideshows in the list:
export default {
  list: [
    require('./oscillatory-motion/OscillatoryMotion'),
    require('./wave-motion/WaveMotion'),
    require('./fluid-mechanics/FluidMechanics'),
    require('./temperature-heat/TemperatureHeat'),
    require('./electrostatic-fields/ElectrostaticFields'),
    require('./electric-conductivity/ElectricConductivity'),
    require('./magnetic-field/MagneticField'),
    require('./maxwell-equations/MaxwellEquations'),
    require('./relativity/Relativity'),
    require('./optics/Optics'),
    require('./photoelectric/photoelectric'),
    require('./atom-physics/Atom-physics'),
    require('./nuclear-physics/Nuclear-physics'),
    require('./laser-cooling/laser-cooling'),
    require('./lab-f4/LaboratoryModernPhysics'),
    // require('./exercises-waves/ExercisesWaves'),
    require('./optomechatronics-intro/Introduction'),
    require('./optomechatronics-optics/Optics'),
    require('./optomechatronics-machine-vision/MachineVision'),
    require('./optomechatronics-mechatronic-elements/MechatronicElements'),
    require('./optomechatronics-optomechartonic-integration/OptomechatronicIntegration'),
    // require('./mecatronica-computacional-modelado/Modelado'),
    // require('./mecatronica-computacional-paradigmas/Paradigmas'),
    require('./mecatronica-computacional-dae-systems/Dae-systems'),
    require('./open-modelica-intro/OpenModelicaIntro'),
    require('./om-intro-circuits/OMIntroCircuits'),
    // require('./mecatronica-computacional-AFM/AtomicForceMicroscope'),
    // require('./mc-optom-functional-units/functional-units'),
    // require('./gms/gms'),
    require('./vision-systems/visionSystems'),
    require('./vision-systems-imagej/imagej'),
    require('./vision-systems-point/pointoperations'),
    require('./vision-systems-spatial-filters/spatialFilters'),
    require('./vision-systems-edges-contours/edgesContours'),
    require('./vision-systems-corner-detection/cornerDetection'),
    require('./vision-systems-hough-transform/houghTransform'),
    require('./vision-systems-morph/morphFilters'),
    require('./vision-systems-regions-binary/regionBinary'),
    require('./vision-systems-fourier/fourier'),
    // require('./vision-systems-lab/visionSystemsLab'),
    require('./introduction/Introduction'),
    require('./comming-soon/CommingSoon')
  ]
}

