// This is the list of all slideshows that will be registered on the
// website, don't forget to register your new slideshows in the list:
export default {
  list: [
    require('./oscillatory-motion/OscillatoryMotion'),
    require('./wave-motion/WaveMotion'),
    require('./fluid-mechanics/FluidMechanics'),
    require('./temperature-heat/TemperatureHeat'),
    require('./electrostatic-fields/ElectrostaticFields'),
    require('./electric-conductivity/ElectricConductivity'),
    require('./magnetic-field/MagneticField'),
    require('./maxwell-equations/MaxwellEquations'),
    // require('./relativity/Relativity'),
    // require('./optics/Optics'),
    // require('./photoelectric/photoelectric'),
    // require('./atom-physics/Atom-physics'),
    // require('./nuclear-physics/Nuclear-physics'),
    require('./Analytic-geometry-i/AnalyticGeometryI'),
    require('./Analytic-geometry-ii/AnalyticGeometryII'),
    require('./Analytic-geometry-iii/AnalyticGeometryIII'),
    require('./Differential-calculus-i/DifferentialCalculusI'),
    require('./Differential-calculus-ii/DifferentialCalculusII'),
    require('./Differential-Calculus-iii/DifferentialCalculusIII'),
    // require('./laser-cooling/laser-cooling'),
    // require('./lab-f4/LaboratoryModernPhysics'),
    // require('./exercises-waves/ExercisesWaves'),
    require('./MecComp-intro-modelica/intro-modelica'),
    require('./MecComp-atomic-modelica/atomic-modelica'),
    require('./MecComp-hybrid-modelica/hybrid-modelica'),
    require('./MecComp-systems-modelica/systems-modelica'),
    // require('./OM-ContinuousTimeModeling/ContinuousTimeModeling'),
    // require('./open-modelica-intro/OpenModelicaIntro'),
    // require('./optomechatronics-om-i/OpenModelica1'),
    // require('./optomechatronics-om-causality/OpenModelicaCausality'),
    // require('./optomechatronics-om-ii/OpenModelica2'),
    require('./optomechatronics-intro/Introduction'),
    require('./optomechatronics-optics/Optics'),
    require('./optomechatronics-machine-vision/MachineVision'),
    require('./optomechatronics-mechatronic-elements/MechatronicElements'),
    require('./mc-optom-functional-units/functional-units'),
    require('./optomechatronics-optomechartonic-integration/OptomechatronicIntegration'),
    require('./mecatronica-computacional-modelado/Modelado'),
    // require('./mecatronica-computacional-paradigmas/Paradigmas'),
    require('./mecatronica-computacional-dae-systems/Dae-systems'),
    require('./om-intro-circuits/OMIntroCircuits'),
    require('./om-model-systems/OMModelSystems'),
    // require('./vision-systems/visionSystems'),
    require('./vision-systems-imagej/imagej'),
    require('./vision-systems-point/pointoperations'),
    require('./vision-systems-spatial-filters/spatialFilters'),
    // require('./vision-systems-edges-contours/edgesContours'),
    // require('./vision-systems-corner-detection/cornerDetection'),
    // require('./vision-systems-hough-transform/houghTransform'),
    // require('./vision-systems-feature-detectors/featureDetectors'),
    // require('./vision-systems-morph/morphFilters'),
    // require('./vision-systems-regions-binary/regionBinary'),
    // require('./vision-systems-fourier/fourier'),
    require('./computer-vision-intro/computerVisionIntro'),
    // require('./computer-vision-image-formation/ImageFormation'),
    // require('./vision-systems-lab/visionSystemsLab'),
    // require('./introduction/Introduction'),
    // require('./comming-soon/CommingSoon'),
    require('./quantum-computing/QuantumComputing'),
    require('./gms/gms')
  ]
}

